runtime: nodejs14
env: standard
entrypoint: npm run start:prod
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: automatic
inbound_services:
  - warmup