version: 1.0.0
boundedContextName: o-auth
moduleName: application
moduleNames: applications
aggregateProperties:
  - name: id
    type: id
    primaryKey: true
    length: 36
    nullable: false
  - name: name
    type: varchar
    maxLength: 255
    nullable: false
  - name: code
    type: varchar
    maxLength: 20
    nullable: false
  - name: secret
    type: varchar
    maxLength: 90
    nullable: false
  - name: is_master
    type: boolean
    nullable: false
  - name: created_at
    type: timestamp
    nullable: true
  - name: updated_at
    type: timestamp
    nullable: true
  - name: deleted_at
    type: timestamp
    nullable: true
