import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { UpdateMessageDetailCommand } from './update-message-detail.command';
import { UpdateMessageDetailService } from './update-message-detail.service';
import {
    MessageDetailId,
    MessageDetailTenantId,
    MessageDetailTenantCode,
    MessageDetailSystemId,
    MessageDetailSystemName,
    MessageDetailScenario,
    MessageDetailExecutionId,
    MessageDetailExecutionType,
    MessageDetailExecutionExecutedAt,
    MessageDetailExecutionMonitoringStartAt,
    MessageDetailExecutionMonitoringEndAt,
    MessageDetailFlowHash,
    MessageDetailFlowParty,
    MessageDetailFlowReceiverParty,
    MessageDetailFlowComponent,
    MessageDetailFlowReceiverComponent,
    MessageDetailFlowInterfaceName,
    MessageDetailFlowInterfaceNamespace,
    MessageDetailStatus,
    MessageDetailRefMessageId,
    MessageDetailDetail,
    MessageDetailExample,
    MessageDetailStartTimeAt,
    MessageDetailDirection,
    MessageDetailErrorCategory,
    MessageDetailErrorCode,
    MessageDetailErrorLabel,
    MessageDetailNode,
    MessageDetailProtocol,
    MessageDetailQualityOfService,
    MessageDetailReceiverParty,
    MessageDetailReceiverComponent,
    MessageDetailReceiverInterface,
    MessageDetailReceiverInterfaceNamespace,
    MessageDetailRetries,
    MessageDetailSize,
    MessageDetailTimesFailed,
    MessageDetailNumberMax,
    MessageDetailNumberDays,
    MessageDetailCreatedAt,
    MessageDetailUpdatedAt,
    MessageDetailDeletedAt,
} from './../../domain/value-objects';

@CommandHandler(UpdateMessageDetailCommand)
export class UpdateMessageDetailCommandHandler implements ICommandHandler<UpdateMessageDetailCommand>
{
    constructor(
        private readonly updateMessageDetailService: UpdateMessageDetailService,
    ) {}

    async execute(command: UpdateMessageDetailCommand): Promise<void>
    {
        // call to use case and implements ValueObjects
        await this.updateMessageDetailService.main(
            {
                id: new MessageDetailId(command.payload.id),
                tenantId: new MessageDetailTenantId(command.payload.tenantId, { undefinable: true }),
                tenantCode: new MessageDetailTenantCode(command.payload.tenantCode, { undefinable: true }),
                systemId: new MessageDetailSystemId(command.payload.systemId, { undefinable: true }),
                systemName: new MessageDetailSystemName(command.payload.systemName, { undefinable: true }),
                scenario: new MessageDetailScenario(command.payload.scenario),
                executionId: new MessageDetailExecutionId(command.payload.executionId, { undefinable: true }),
                executionType: new MessageDetailExecutionType(command.payload.executionType, { undefinable: true }),
                executionExecutedAt: new MessageDetailExecutionExecutedAt(command.payload.executionExecutedAt, { undefinable: true }, {removeTimezone: command.cQMetadata.timezone}),
                executionMonitoringStartAt: new MessageDetailExecutionMonitoringStartAt(command.payload.executionMonitoringStartAt, { undefinable: true }, {removeTimezone: command.cQMetadata.timezone}),
                executionMonitoringEndAt: new MessageDetailExecutionMonitoringEndAt(command.payload.executionMonitoringEndAt, { undefinable: true }, {removeTimezone: command.cQMetadata.timezone}),
                flowHash: new MessageDetailFlowHash(command.payload.flowHash, { undefinable: true }),
                flowParty: new MessageDetailFlowParty(command.payload.flowParty),
                flowReceiverParty: new MessageDetailFlowReceiverParty(command.payload.flowReceiverParty),
                flowComponent: new MessageDetailFlowComponent(command.payload.flowComponent, { undefinable: true }),
                flowReceiverComponent: new MessageDetailFlowReceiverComponent(command.payload.flowReceiverComponent),
                flowInterfaceName: new MessageDetailFlowInterfaceName(command.payload.flowInterfaceName, { undefinable: true }),
                flowInterfaceNamespace: new MessageDetailFlowInterfaceNamespace(command.payload.flowInterfaceNamespace, { undefinable: true }),
                status: new MessageDetailStatus(command.payload.status, { undefinable: true }),
                refMessageId: new MessageDetailRefMessageId(command.payload.refMessageId),
                detail: new MessageDetailDetail(command.payload.detail),
                example: new MessageDetailExample(command.payload.example),
                startTimeAt: new MessageDetailStartTimeAt(command.payload.startTimeAt, {}, {removeTimezone: command.cQMetadata.timezone}),
                direction: new MessageDetailDirection(command.payload.direction, { undefinable: true }),
                errorCategory: new MessageDetailErrorCategory(command.payload.errorCategory),
                errorCode: new MessageDetailErrorCode(command.payload.errorCode),
                errorLabel: new MessageDetailErrorLabel(command.payload.errorLabel),
                node: new MessageDetailNode(command.payload.node),
                protocol: new MessageDetailProtocol(command.payload.protocol),
                qualityOfService: new MessageDetailQualityOfService(command.payload.qualityOfService),
                receiverParty: new MessageDetailReceiverParty(command.payload.receiverParty),
                receiverComponent: new MessageDetailReceiverComponent(command.payload.receiverComponent),
                receiverInterface: new MessageDetailReceiverInterface(command.payload.receiverInterface),
                receiverInterfaceNamespace: new MessageDetailReceiverInterfaceNamespace(command.payload.receiverInterfaceNamespace),
                retries: new MessageDetailRetries(command.payload.retries),
                size: new MessageDetailSize(command.payload.size),
                timesFailed: new MessageDetailTimesFailed(command.payload.timesFailed),
                numberMax: new MessageDetailNumberMax(command.payload.numberMax),
                numberDays: new MessageDetailNumberDays(command.payload.numberDays),
            },
            command.constraint,
            command.cQMetadata,
        )
    }
}