import { CQMetadata } from '@hades/shared/domain/lib/hades.types';

export class CreateChannelsCommand
{
    constructor(
        public readonly payload: {
            id: string,
            hash: string,
            tenantId: string,
            tenantCode: string,
            systemId: string,
            systemName: string,
            party?: string,
            component: string,
            name: string,
            flowHash?: string,
            flowParty?: string,
            flowReceiverParty?: string,
            flowComponent?: string,
            flowReceiverComponent?: string,
            flowInterfaceName?: string,
            flowInterfaceNamespace?: string,
            version?: string,
            adapterType?: string,
            direction?: string,
            transportProtocol?: string,
            messageProtocol?: string,
            adapterEngineName?: string,
            url?: string,
            username?: string,
            remoteHost?: string,
            remotePort?: number,
            directory?: string,
            fileSchema?: string,
            proxyHost?: string,
            proxyPort?: number,
            destination?: string,
            adapterStatus?: string,
            softwareComponentName?: string,
            responsibleUserAccountName?: string,
            lastChangeUserAccount?: string,
            lastChangedAt?: string,
            riInterfaceName?: string,
            riInterfaceNamespace?: string,
        } [],
        public readonly cQMetadata?: CQMetadata,
    ) {}
}